### ISSUE TITLE
Plugin no longer works since a few days

### ISSUE THREAD

**Issue by ZonerZoner** [dradovic/SoundCloud4PS3#3]
Since a few days, the following error occurs. Can you provide a fix for this issue?

08-16 17:49:58  Authentication error: Unable to respond to any of these challenges: {}
08-16 17:49:58  
08-16 17:49:58  javax.xml.transform.TransformerException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.XPath.execute(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(Unknown Source)
08-16 17:49:58      at soundcloud4ps3.Cloud.retrieveEntities(Cloud.java:44)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.addChildren(ResourceFolder.java:47)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.discoverChildren(ResourceFolder.java:39)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1060)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:973)
08-16 17:49:58      at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:895)
08-16 17:49:58      at net.pms.network.RequestV2.answer(RequestV2.java:658)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:288)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:246)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
08-16 17:49:58      at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
08-16 17:49:58      at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
08-16 17:49:58      at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
08-16 17:49:58      at java.lang.Thread.run(Unknown Source)
08-16 17:49:58  Caused by: java.lang.RuntimeException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.NodeSequence.setRoot(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.LocPathIterator.execute(Unknown Source)
08-16 17:49:58      ... 41 more
08-16 17:49:58  ---------
08-16 17:49:58  java.lang.RuntimeException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.NodeSequence.setRoot(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.LocPathIterator.execute(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.XPath.execute(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(Unknown Source)
08-16 17:49:58      at soundcloud4ps3.Cloud.retrieveEntities(Cloud.java:44)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.addChildren(ResourceFolder.java:47)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.discoverChildren(ResourceFolder.java:39)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1060)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:973)
08-16 17:49:58      at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:895)
08-16 17:49:58      at net.pms.network.RequestV2.answer(RequestV2.java:658)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:288)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:246)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
08-16 17:49:58      at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
08-16 17:49:58      at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
08-16 17:49:58      at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
08-16 17:49:58      at java.lang.Thread.run(Unknown Source)
08-16 17:49:58  --------------- linked to ------------------
08-16 17:49:58  javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(Unknown Source)
08-16 17:49:58      at soundcloud4ps3.Cloud.retrieveEntities(Cloud.java:44)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.addChildren(ResourceFolder.java:47)
08-16 17:49:58      at soundcloud4ps3.ResourceFolder.discoverChildren(ResourceFolder.java:39)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1060)
08-16 17:49:58      at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:973)
08-16 17:49:58      at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:895)
08-16 17:49:58      at net.pms.network.RequestV2.answer(RequestV2.java:658)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:288)
08-16 17:49:58      at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:246)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
08-16 17:49:58      at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
08-16 17:49:58      at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
08-16 17:49:58      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
08-16 17:49:58      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
08-16 17:49:58      at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
08-16 17:49:58      at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
08-16 17:49:58      at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
08-16 17:49:58      at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
08-16 17:49:58      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
08-16 17:49:58      at java.lang.Thread.run(Unknown Source)
08-16 17:49:58  Caused by: javax.xml.transform.TransformerException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.XPath.execute(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(Unknown Source)
08-16 17:49:58      ... 39 more
08-16 17:49:58  Caused by: java.lang.RuntimeException: Unable to evaluate expression using this context
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.NodeSequence.setRoot(Unknown Source)
08-16 17:49:58      at com.sun.org.apache.xpath.internal.axes.LocPathIterator.execute(Unknown Source)
08-16 17:49:58      ... 41 more

**Comment by dradovic** [comment]
I'm not developing this project anymore, I'm sorry. From the call-stack I guess something on the SoundCloud side has changed. Is your SC account working? Did they change something in the authorization protocol? Just some hints from the top of my mind...

**Comment by greyslater** [comment]
Hello dradovic,

i came across your great PlugIn when searching something to stream SoundCloud to my Yamaha MusicCast System.
After hours of searching i can't find anything similar (except Smartphone Apps) to archive this Feature and it's a huge pitty that first of all SoundCloud changes their API way too much often and second you can't develope this project anymore :(

Because, i guess, it won't be possible for me to retune your opinion about having a look at the authorization issue :) do you have knowledge of other tools to stream SoundCloud as a DLNA Server to DLNA Clients

Thanks in advance
GreySlater

**Comment by dradovic** [comment]
I'm sorry but I won't be able to help you on this one anymore. I've moved to Brasil and I live out in the back with nature being my multi-media system. I do have Internet but that's barely it :)

**Comment by ZonerZoner** [comment]
Hi GraySlater

I moved to the Logitec Media Server (http://www.mysqueezebox.com/download) where it is possible to install a soundcloud plugin (https://github.com/danielvijge/SqueezeCloud). Maybe this works for your needs too.

Hope this helps

**Comment by greyslater** [comment]
Hi ZonerZoner,

not far away from what i'm searching or it's because i'm doing something wrong :)

For me it's important to stream Soundcloud over UPnP / DLNA to my Yamaha MusicCast System.
Also with installed SoundCloud PlugIn for the LogitechMediaServer and Connection to SoundCloud with my API-Key there are no additional Folders when i search the Server over UPnP / DLNA

That's the main difference here: With PS3MediaServer aka UniversalMediaServer, when you install this PlugIn (SoundCloud4PS3) you get a SoundCloud Folder also over UPnP / DLNA but like you mentioned in your first post here, there is the authentication Problem.
